# Generated by Django 5.1.7 on 2025-04-07 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products_is_sale_products_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='star',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
